import uuid, math, os, re, hashlib, random, requests
from datetime import datetime, timezone, timedelta
from typing import Any, Dict, Optional
from fastapi import APIRouter, Depends, HTTPException, Query, UploadFile, File

AI_SIGNATURES=("midjourney","stable diffusion","stability ai","dall-e","openai","firefly","adobe firefly","comfyui","leonardo ai","ideogram","synthetic media","ai generated","generated by ai","generative ai")
DISPOSABLE_DOMAINS={"mailinator.com","guerrillamail.com","10minutemail.com","tempmail.com","temp-mail.org","yopmail.com","sharklasers.com","trashmail.com","getnada.com","dispostable.com"}

def register_feature_routes(api_router, db, get_current_user, manager, compute_match, user_public, haversine_km, gender_ok):
    async def _other_for_match(m,user):
        oid=[u for u in m.get("user_ids",[]) if u!=user["user_id"]][0]
        return await db.users.find_one({"user_id":oid},{"_id":0,"password_hash":0,"face_descriptor_selfie":0})

    @api_router.post("/auth/validate-email")
    async def validate_email(payload:dict):
        email=(payload.get("email") or "").strip().lower()
        if not re.fullmatch(r"[^\s@]+@[^\s@]+\.[^\s@]{2,}",email): raise HTTPException(status_code=400,detail="Enter a valid email address.")
        domain=email.rsplit("@",1)[1]
        if domain in DISPOSABLE_DOMAINS: raise HTTPException(status_code=400,detail="Temporary/disposable email addresses are not allowed.")
        try:
            resp=requests.get("https://dns.google/resolve",params={"name":domain,"type":"MX"},timeout=5)
            if resp.status_code!=200 or not resp.json().get("Answer"): raise HTTPException(status_code=400,detail="That email domain does not appear to accept email.")
        except HTTPException: raise
        except Exception: pass
        return {"valid":True,"email":email}

    def normalize_phone(value):
        raw=re.sub(r"[^0-9+]","",value or "")
        if raw.startswith("0"): raw="+91"+raw[1:]
        elif raw.startswith("91") and not raw.startswith("+"): raw="+"+raw
        if not re.fullmatch(r"\+91[6-9]\d{9}",raw): raise HTTPException(status_code=400,detail="Enter a valid Indian mobile number.")
        return raw

    @api_router.post("/auth/phone/request-otp")
    async def request_phone_otp(payload:dict):
        phone=normalize_phone(payload.get("phone"))
        sid=os.environ.get("TWILIO_ACCOUNT_SID"); token=os.environ.get("TWILIO_AUTH_TOKEN"); service=os.environ.get("TWILIO_VERIFY_SERVICE_SID")
        if not sid or not token or not service: raise HTTPException(status_code=503,detail="Phone verification is not configured yet. Add the Twilio Verify settings in Render.")
        try:
            resp=requests.post(f"https://verify.twilio.com/v2/Services/{service}/Verifications",auth=(sid,token),data={"To":phone,"Channel":"sms"},timeout=10)
            if resp.status_code>=400: raise HTTPException(status_code=400,detail="Could not send OTP. Please check the number and try again.")
        except HTTPException: raise
        except Exception: raise HTTPException(status_code=502,detail="OTP service is temporarily unavailable.")
        await db.phone_otps.update_one({"phone":phone},{"$set":{"phone":phone,"created_at":datetime.now(timezone.utc).isoformat(),"expires_at":(datetime.now(timezone.utc)+timedelta(minutes=10)).isoformat(),"verified":False,"attempts":0}},upsert=True)
        return {"ok":True,"phone":phone}

    @api_router.post("/auth/phone/verify-otp")
    async def verify_phone_otp(payload:dict):
        phone=normalize_phone(payload.get("phone"));code=str(payload.get("otp") or "").strip()
        if not re.fullmatch(r"\d{6}",code): raise HTTPException(status_code=400,detail="Enter the 6-digit OTP.")
        sid=os.environ.get("TWILIO_ACCOUNT_SID"); token=os.environ.get("TWILIO_AUTH_TOKEN"); service=os.environ.get("TWILIO_VERIFY_SERVICE_SID")
        if not sid or not token or not service: raise HTTPException(status_code=503,detail="Phone verification is not configured yet.")
        try:
            resp=requests.post(f"https://verify.twilio.com/v2/Services/{service}/VerificationCheck",auth=(sid,token),data={"To":phone,"Code":code},timeout=10)
            body=resp.json()
            if resp.status_code>=400 or body.get("status")!="approved": raise HTTPException(status_code=400,detail="Incorrect or expired OTP.")
        except HTTPException: raise
        except Exception: raise HTTPException(status_code=502,detail="OTP service is temporarily unavailable.")
        await db.phone_otps.update_one({"phone":phone},{"$set":{"verified":True,"verified_at":datetime.now(timezone.utc).isoformat()}})
        return {"ok":True,"phone":phone}

    @api_router.post("/auth/phone/link")
    async def link_phone(payload:dict,user:dict=Depends(get_current_user)):
        phone=normalize_phone(payload.get("phone"));record=await db.phone_otps.find_one({"phone":phone,"verified":True},{"_id":0})
        if not record: raise HTTPException(status_code=400,detail="Please verify this phone number with OTP first.")
        existing=await db.users.find_one({"phone":phone,"user_id":{"$ne":user["user_id"]}},{"_id":0})
        if existing: raise HTTPException(status_code=400,detail="This phone number is already linked to another account.")
        await db.users.update_one({"user_id":user["user_id"]},{"$set":{"phone":phone,"phone_verified":True}});return {"ok":True,"phone":phone}

    def report(a,b):
        def pct(x): return max(0,min(100,round(x)))
        clean=pct(100-abs(int(a.get("cleanliness") or 3)-int(b.get("cleanliness") or 3))*25)
        amin,amax=int(a.get("budget_min") or 0),int(a.get("budget_max") or 0); bmin,bmax=int(b.get("budget_min") or 0),int(b.get("budget_max") or 0)
        overlap=max(0,min(amax,bmax)-max(amin,bmin)); union=max(amax,bmax)-min(amin,bmin) or 1
        rent=pct(overlap/union*100); same=lambda x,y: bool(x is not None and y is not None and x==y)
        return [{"key":"cleanliness","label":"Cleanliness","value":clean,"text":"Very similar standards" if clean>=80 else "Some difference in standards"},{"key":"rent","label":"Rent budget","value":rent,"text":"Budgets overlap" if rent>0 else "Budgets do not overlap"},{"key":"food","label":"Food","value":100 if same(a.get("food_pref"),b.get("food_pref")) else 45,"text":"Same preference" if same(a.get("food_pref"),b.get("food_pref")) else "Different preference"},{"key":"sleep","label":"Sleep schedule","value":100 if same(a.get("sleep_schedule"),b.get("sleep_schedule")) else 50,"text":"Same rhythm" if same(a.get("sleep_schedule"),b.get("sleep_schedule")) else "Different rhythm"},{"key":"social","label":"Social style","value":100 if same(a.get("social_level"),b.get("social_level")) else 55,"text":"Similar social energy" if same(a.get("social_level"),b.get("social_level")) else "Some difference"}]

    def city_norm(v):
        v=(v or "").strip().lower().replace(" ","");return "bangalore" if v in {"bangalore","bengaluru","bengalooru"} else v

    @api_router.get("/discover-v2")
    async def discover_v2(user:dict=Depends(get_current_user),radius_km:Optional[int]=None,food:Optional[str]=None,smoking:Optional[str]=None,drinking:Optional[str]=None,housing:Optional[str]=None,budget_min:Optional[int]=None,budget_max:Optional[int]=None,cleanliness:Optional[str]=None,pets_ok:Optional[str]=None,male_guests_ok:Optional[str]=None,family_visits_ok:Optional[str]=None,hosts_parties:Optional[str]=None,sleep_schedule:Optional[str]=None):
        swiped=await db.swipes.find({"user_id":user["user_id"]},{"_id":0,"target_user_id":1}).to_list(5000);exclude={s["target_user_id"] for s in swiped}|{user["user_id"]};candidates=await db.users.find({"user_id":{"$nin":list(exclude)},"onboarding_done":True,"profile_complete":True},{"_id":0,"password_hash":0,"face_descriptor_selfie":0}).to_list(1000)
        filters={k:[x for x in (v or "").split(",") if x] for k,v in {"food":food,"smoking":smoking,"drinking":drinking,"housing":housing,"cleanliness":cleanliness,"pets_ok":pets_ok,"male_guests_ok":male_guests_ok,"family_visits_ok":family_visits_ok,"hosts_parties":hosts_parties,"sleep_schedule":sleep_schedule}.items()};r=radius_km if radius_km is not None else int(user.get("radius_km") or 5);scored=[]
        for c in candidates:
            if city_norm(user.get("city"))!=city_norm(c.get("city")) or not gender_ok(user,c) or not gender_ok(c,user):continue
            if filters["food"] and c.get("food_pref") not in filters["food"]:continue
            if filters["smoking"] and c.get("smoking") not in filters["smoking"]:continue
            if filters["drinking"] and c.get("drinking") not in filters["drinking"]:continue
            if filters["housing"] and c.get("housing_status") not in filters["housing"]:continue
            if filters["cleanliness"] and str(c.get("cleanliness")) not in filters["cleanliness"]:continue
            if filters["pets_ok"] and str(bool(c.get("pets_ok"))).lower() not in [x.lower() for x in filters["pets_ok"]]:continue
            if filters["male_guests_ok"] and str(bool(c.get("male_guests_ok"))).lower() not in [x.lower() for x in filters["male_guests_ok"]]:continue
            if filters["family_visits_ok"] and str(bool(c.get("family_visits_ok"))).lower() not in [x.lower() for x in filters["family_visits_ok"]]:continue
            if filters["hosts_parties"] and c.get("hosts_parties") not in filters["hosts_parties"]:continue
            if filters["sleep_schedule"] and c.get("sleep_schedule") not in filters["sleep_schedule"]:continue
            if budget_min is not None and int(c.get("budget_max") or 0)<int(budget_min):continue
            if budget_max is not None and int(c.get("budget_min") or 0)>int(budget_max):continue
            m=compute_match(user,c);scored.append({"user":c,"score":m["score"],"highlights":m["highlights"],"distance_km":m["distance_km"]})
        same_loc=(user.get("locality") or "").strip().lower();primary=[];nearby=[]
        for s in scored:
            loc=(s["user"].get("locality") or "").strip().lower();d=s["distance_km"]
            if loc==same_loc or (d is not None and d<=r):primary.append(s)
            else:nearby.append(s)
        primary.sort(key=lambda x:(0 if (x["user"].get("locality") or "").strip().lower()==same_loc else 1,x["distance_km"] if x["distance_km"] is not None else 9999,-x["score"]));nearby.sort(key=lambda x:(x["distance_km"] if x["distance_km"] is not None else 9999,-x["score"]));return {"primary":primary[:50],"nearby":nearby[:50],"fallback_message":None if primary else (f"No one in {user.get('locality') or 'your area'} yet — showing nearby profiles." if nearby else None)}

    @api_router.get("/matches-v2")
    async def matches_v2(user:dict=Depends(get_current_user)):
        ms=await db.matches.find({"user_ids":user["user_id"]},{"_id":0}).sort("created_at",-1).to_list(200);out=[]
        for m in ms:
            other=await _other_for_match(m,user);last=await db.messages.find_one({"match_id":m["match_id"]},{"_id":0},sort=[("created_at",-1)]);unread=await db.messages.count_documents({"match_id":m["match_id"],"sender_id":{"$ne":user["user_id"]},"read_by":{"$ne":user["user_id"]}});out.append({"match":m,"other":user_public(other or {}),"last_message":last,"unread_count":unread,"match_report":report(user,other or {})})
        return out
    @api_router.get("/messages-v2/{match_id}")
    async def messages_v2(match_id:str,user:dict=Depends(get_current_user)):
        match=await db.matches.find_one({"match_id":match_id,"user_ids":user["user_id"]},{"_id":0})
        if not match:raise HTTPException(status_code=404,detail="Match not found")
        return await db.messages.find({"match_id":match_id},{"_id":0}).sort("created_at",1).to_list(1000)
    @api_router.post("/messages-v2/{match_id}/read")
    async def mark_messages_read(match_id:str,user:dict=Depends(get_current_user)):
        match=await db.matches.find_one({"match_id":match_id,"user_ids":user["user_id"]},{"_id":0})
        if not match:raise HTTPException(status_code=404,detail="Match not found")
        await db.messages.update_many({"match_id":match_id,"sender_id":{"$ne":user["user_id"]}},{"$addToSet":{"read_by":user["user_id"]}});return {"ok":True}
    @api_router.post("/messages-v2")
    async def send_message_v2(data:dict,user:dict=Depends(get_current_user)):
        match_id=data.get("match_id");text=(data.get("text") or "").strip()
        if not match_id or not text:raise HTTPException(status_code=400,detail="Message is required")
        match=await db.matches.find_one({"match_id":match_id,"user_ids":user["user_id"]},{"_id":0})
        if not match:raise HTTPException(status_code=404,detail="Match not found")
        msg={"message_id":f"msg_{uuid.uuid4().hex[:12]}","match_id":match_id,"sender_id":user["user_id"],"text":text,"created_at":datetime.now(timezone.utc).isoformat(),"read_by":[user["user_id"]]};await db.messages.insert_one(msg);msg.pop("_id",None);other=[u for u in match["user_ids"] if u!=user["user_id"]][0];await manager.push(other,{"type":"message","message":msg});return msg
    @api_router.post("/upload-v2")
    async def upload_v2(file:UploadFile=File(...),main:bool=False,user:dict=Depends(get_current_user)):
        ext=file.filename.rsplit(".",1)[-1].lower() if "." in file.filename else "jpg"
        if ext not in ("jpg","jpeg","png","webp"):raise HTTPException(status_code=400,detail="Unsupported image format")
        data=await file.read()
        if len(data)>8*1024*1024:raise HTTPException(status_code=400,detail="File too large (max 8MB)")
        if main:
            sample=data[:1024*1024].decode("latin1",errors="ignore").lower()
            if any(sig in sample for sig in AI_SIGNATURES):raise HTTPException(status_code=400,detail="This image appears to contain AI-generation metadata. Please use a real photo taken by you.")
        from pathlib import Path
        storage_dir=Path(os.environ.get("STORAGE_DIR",Path(__file__).parent/"storage"));storage_dir.mkdir(parents=True,exist_ok=True)
        path=f"flatmate-plus/uploads/{user['user_id']}/{uuid.uuid4().hex}.{ext}";full=storage_dir/path;full.parent.mkdir(parents=True,exist_ok=True);full.write_bytes(data);ct=file.content_type or f"image/{'jpeg' if ext in ('jpg','jpeg') else ext}"
        await db.files.insert_one({"id":str(uuid.uuid4()),"user_id":user["user_id"],"storage_path":path,"content_type":ct,"size":len(data),"is_deleted":False,"created_at":datetime.now(timezone.utc).isoformat()});return {"path":path}
