import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api, fileUrl } from "@/lib/api";
import BottomNav from "@/components/BottomNav";
import { MessageCircle, Sparkles } from "lucide-react";

export default function Matches() {
  const [items,setItems]=useState([]); const [loading,setLoading]=useState(true);
  useEffect(()=>{api.get("/matches").then(({data})=>setItems(data)).catch(e=>console.error("Failed to load matches",e)).finally(()=>setLoading(false));},[]);
  const hasUnread=items.some(x=>(x.unread_count||0)>0);
  return <div className="app-shell pb-32"><div className="px-6 pt-8 pb-4"><div className="flex items-center gap-2"><div className="font-mono-label text-primary">MATCHES</div>{hasUnread&&<span className="w-2.5 h-2.5 rounded-full bg-destructive" aria-label="Unread messages"/>}</div><h1 className="text-2xl font-display font-extrabold leading-tight">Your people</h1></div><div className="px-6">{loading?<div className="text-sm text-muted-foreground py-10 text-center">Loading…</div>:items.length===0?<div className="mt-6 p-8 rounded-3xl bg-card border text-center"><MessageCircle className="w-8 h-8 mx-auto text-muted-foreground"/><div className="font-display font-bold text-lg mt-2">No matches yet</div><p className="text-sm text-muted-foreground mt-1">Head to Discover and start swiping.</p></div>:<div className="space-y-3">{items.map(({match,other,last_message,unread_count=0})=><Link data-testid={`match-item-${match.match_id}`} key={match.match_id} to={`/chat/${match.match_id}`} className="relative flex items-center gap-3 p-3 rounded-2xl bg-card border hover:bg-secondary transition-colors"><div className="w-14 h-14 rounded-2xl overflow-hidden bg-secondary shrink-0">{other?.photos?.[0]?<img src={fileUrl(other.photos[0])} className="w-full h-full object-cover" alt={other.name}/>:<div className="w-full h-full grid place-items-center font-display font-extrabold text-xl bg-primary/15 text-primary">{other?.name?.[0]}</div>}</div><div className="flex-1 min-w-0"><div className="flex items-center gap-2"><div className="font-display font-bold truncate">{other?.name}</div><div className="flex items-center gap-0.5 text-primary text-xs font-semibold"><Sparkles className="w-3 h-3"/>{match.score}%</div></div><div className={`text-sm truncate ${unread_count>0?"font-semibold text-foreground":"text-muted-foreground"}`}>{last_message?last_message.text:"Say hi 👋"}</div></div>{unread_count>0&&<span className="absolute top-3 right-3 w-2.5 h-2.5 rounded-full bg-destructive" aria-label={`${unread_count} unread messages`}/>}</Link>)}</div>}</div><BottomNav/></div>;
}
